# Generated by Django 3.2 on 2021-04-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_description',
            field=models.TextField(),
        ),
    ]
