# Generated by Django 3.2 on 2021-04-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_homework_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='instructor',
        ),
    ]
