# Generated by Django 3.2 on 2021-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_homework_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
