# Generated by Django 3.2 on 2021-04-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_homework_homework_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homework_due_date',
            new_name='homework_due_datetime',
        ),
    ]
