# Generated by Django 3.2 on 2021-04-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_homeworksubmission_submission_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework'),
        ),
    ]
