# Generated by Django 3.2 on 2021-04-30 03:07

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_homeworksubmission_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_file_upload',
            field=models.FileField(upload_to=courses.models.path_and_rename('/documents')),
        ),
    ]
