# Generated by Django 3.2 on 2021-04-30 03:47

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_homeworksubmission_submission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_file_upload',
            field=models.FileField(upload_to=courses.models.path_and_rename('documents/')),
        ),
    ]
