# Generated by Django 3.2 on 2021-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_homeworksubmission_submission_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='submission_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='submission_result',
            field=models.FloatField(null=True),
        ),
    ]
