# Generated by Django 3.2 on 2021-04-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210430_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_due_datetime',
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_due_date',
            field=models.DateField(null=True),
        ),
    ]
