# Generated by Django 3.2 on 2021-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210430_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='content_created_datetime',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_due_date',
        ),
        migrations.AddField(
            model_name='test',
            name='test_instruction',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
    ]
